---
- name: worker nodes
  hosts: localhost
  remote_user: root

  tasks:
   - name: Insert after regex, backup, and validate
     lineinfile:
      path: /opt/ansible/kubernetes/apache2.conf
      regexp: '^#For PHP5'
      insertbefore: 'LoadFile "C:/www/php5/php5ts.dll"'
      line: 'PasswordAuthentication no'

   - name: Restart service containerd
     service:
      name: containerd
      state: restarted


   - name: Reboot the server
     reboot:


   - name: stop service kubelet
     service:
      name: kubelet
      state: stopped

   - name: Execute echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
     shell: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
  
   - name: Ansible insert a line
     lineinfile:
      path: /opt/ansible/kubernetes/kube
      backrefs: true
      regexp: '^(.*)$'
      line: '\1 --cri-socket /run/containerd/containerd.sock'
      create: true
   

   - name: Copy join command from Ansiblehost to the worker nodes.
     become: yes
     copy:
       src: /tmp/kubernetes_join_command
       dest: /tmp/kubernetes_join_command
       mode: 0777

   - name: Join the Worker nodes to the cluster.
     become: yes
     command: sh /tmp/kubernetes_join_command
     register: joined_or_not