---
-   hosts: localhost
    become: yes
    become_user: root
    tasks:
    - name: copy resolv.conf file to /run/systemd/resolve/resolv.conf after reboot server.
      cron:
        user: 'root'
        name: 'Resolv.conf'
        special_time: reboot
        job: 'ln -s  /etc/resolv.conf /run/systemd/resolve/resolv.conf'
        state: present
      tags: cronjob