    - name: Update apt package
      shell: sudo apt-get update -y

    - name: install haproxy
      become: yes
      apt: name=haproxy state=present

    - name: Stop haproxy service
      shell: sudo systemctl stop haproxy

    - name: Create "{{ my_file }}"
      become: yes
      template:
        src: "{{ my_template }}"
        dest: "{{ my_file }}"
        owner: root
        group: root
        mode: "0644"
    - name: start haproxy service
      shell: sudo systemctl start haproxy
